;
; config.ini
;
; This is the configuration file for the ExploreBgToolRe(dux), a refactored version of the original ExplorerBgTool by Maple.
; This project (ExploreBgToolRe) hosted at https://github.com/lpierge/ExplorerBgToolRe
; Luca Piergentili, 18/06/2026
;
; Notes (new features):
;
; - A dedicated command-line loader (ebtl.exe) that can install, register, unregister, reload the DLL, and restart Explorer,
;   automatically requesting administrator privileges when needed.
; - Ability to specify which programs are allowed to load the DLL using a whitelist.
; - A specific list for programs allowed to use the DLL in Open/Save dialogs.
; - Configuration settings are reloaded every time Explorer opens a new folder, so changes to this config file are applied in 
;   real time. This includes the images for the special folders. The only exception is the image list, which is loaded only 
;   once when the DLL is initialized, either at Windows startup or when the DLL is explicitly restarted via the ebtl utility.
; - Support for setting different transparency levels for the Explorer window when it is in the foreground or background.
; - Limit on the maximum number of images that can be loaded into the list (max 128, default 64) because each bitmap’s memory
;   is allocated in Explorer’s address space and with no limit, Explorer could suffer a memory overhead, leading to poor 
;   performance or even crashes.
; - Ability to specify which image formats should be considered when loading images into the list.
; - Possibility to assign an image using its full pathname for special folders, without requiring the image to be in the 
;   default images directory.
; - Support for using the wildcard character * (asterisk) at the end of a special folder name (using the standard name, not 
;   the CLSID) to apply the same image to all its subfolders.

[load]
; list here the programs allowed to load the DLL (only the program name, no path), do not mess with this field
whitelist=regsvr32.exe,ebtl.exe

; to enable the DLL extension in the file dialog for open/save (true/false)
filedialog=true

; programs allowed to use the DLL extension in the file dialog for open/save
; specify only the program name, no path
; programs listed here must be closed when installing, registering, unregistering the DLL or restarting the Explorer
filedialoglist=notepad.exe

; show or ignore errors (true/false)
showerrors=true

[explorer]
; transparency value for the Explorer window when in the background (0=invisible, 255=solid)
backgroundalpha=128
; transparency value for the Explorer window when in the foreground (0=invisible, 255=solid)
foregroundalpha=255

[image]
; maximum number of images that can be loaded (allowed range 1 to 128)
maximages=64

; list of graphics formats to search for when loading images, DO NOT use large formats like BMP
; the following list includes all the formats currently supported
graphicsformats=*.png,*.jpg,*.jpeg,*.jpe,*.jfif,*.gif

; image display mode: 0=top-left, 1=top-right, 2=bottom-left, 3=bottom-right, 4=center, 5=zoom, 6=fill
; notes:
; 4 -> center: draw the image in the original size, no dynamic resize
; 5 -> zoom: stretch without mantaining the aspect ratio
; 6 -> fill: fit horizontally mantaining the aspect ratio
displaymode=3

; image transparency (0=invisible, 255=solid)
alphablend=255

; specify whether the images are displayed in random mode (at least 2 images required)
; if false, only the first image is used for all the folders
; images must reside in the "Image" subdirectory of the directory where the DLL is installed or in the custom folder (see below)
random=true

; use a custom folder for images instead of the default .\Image folder (if empty defaults to .\Image)
customfolder=

; enable the use of special folders (true/false), see below
specialfolders=true

; images for special folders could be located everywhere and must be specified using the full pathname
; these images will not be used for any other standard folder, unless you copy them in the .\Image or custom directory
; special folders must be specified using the CLSID or the canonical pathname, both enclosed with []

; This PC
; (quick access: C:\Windows\explorer.exe shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D})
[::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]
img=C:\ExplorerBgToolRe\Chibi\chibi01.png

; Documents
; (quick access: C:\Windows\explorer.exe shell:::{450D8FBA-AD25-11D0-98A8-0800361B1103})
[::{450D8FBA-AD25-11D0-98A8-0800361B1103}]
img=C:\ExplorerBgToolRe\Chibi\chibi02.jpg

; Quick access
; (quick access: C:\Windows\explorer.exe shell:::{679F85CB-0220-4080-B29B-5540CC05AAB6})
[::{679F85CB-0220-4080-B29B-5540CC05AAB6}]
img=C:\ExplorerBgToolRe\Chibi\chibi03.jpg

; Network
; (quick access: C:\Windows\explorer.exe shell:::{F02C1A0D-BE21-4350-88B0-7367FC96EF3C})
[::{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}]
img=C:\ExplorerBgToolRe\Chibi\chibi04.jpg

; Recycle Bin
[::{645FF040-5081-101B-9F08-00AA002F954E}]
img=C:\ExplorerBgToolRe\Chibi\chibi05.jpg

; standard directory
; adding an * at the end of the path makes the image apply to that folder and all its subdirectories
[C:\Windows*]
img=C:\ExplorerBgToolRe\Chibi\notchibi.png
[C:\ExplorerBgToolRe*]
img=C:\ExplorerBgToolRe\Chibi\notchibi.png

; Control Panel
; do not use, WILL NOT WORK, because the Control Panel is handled directly with DirectUI by Windows
;[::{5399E694-6CE5-4D6C-8FCE-1D8870FDCBA0}]
;[::{21EC2020-3AEA-1069-A2DD-08002B30309D}]
;img=C:\ExplorerBgToolRe\Rabbids\Rayman_Raving_Rabbids_BlueSun.jpg
